### PR TITLE
1.2 branch

### PR DESCRIPTION
**Pull request by evilfer**
Creates a new rest endpoint supporting JWT authentication.
This can be used by Android apps to login against nquire-it using Google identities and the native Androidi account selection interface.

Requires updating ```pom.xml```, see changes to ```pom.TEMPLATE.xml```.

### CODE REVIEW

**Comment by nfreear** [comment]
Hi Eloy / @evilfer,

Thank you. Apologies for the delay. Just going to merge, build and put on the approval server ~ https://github.com/IET-OU/nquire-web-compiled


N.

**Comment by nfreear** [comment]
Hi @evilfer,

I've compiled and put the updated code on the test server. Tomcat has failed to restart cleanly (404).

Should there only be three updated Java class files, or are there more?

* https://github.com/IET-OU/nquire-web-compiled/commit/4b84f08005414347da4dda367b4d97235847d20f

See part of a log file below. I don't have time to debug further at the moment.

Yours,

Nick


---
catalina.2018-03-10.log:

```
...
Mar 01, 2018 11:16:00 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.76
Mar 01, 2018 11:16:00 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat/webapps/ROOT
Mar 01, 2018 11:16:06 AM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that 
were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Mar 01, 2018 11:16:14 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Mar 01, 2018 11:16:14 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
Mar 01, 2018 11:16:14 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application wa
s stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Mar 01, 2018 11:16:14 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. Th
is is very likely to create a memory leak.
Mar 01, 2018 11:16:14 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /var/lib/tomcat/webapps/ROOT has finished in 13,138 ms
Mar 01, 2018 11:16:14 AM org.apache.coyote.AbstractProtocol start
...
```

---
(CC, @kevmcleod, for interest!)

**Comment by evilfer** [comment]
Hi Nick,

Besides the java code, I had to add one library to pom.xml, but this file
is not in the repo (see
https://github.com/evilfer/nquire-web-source/commit/c2ab709b7c60b208128ac15e98c621f40e9b4df9#diff-786d8b79384207fc9a1c440adf1faab8R325
).
If this hasn't been replicated in the server's pom.xml, I imagine that
might be the cause of "SEVERE: One or more listeners failed to start."

If that doesn't fix it, could you let me know the Java/Tomcat version to
test the code with those?

Hope this helps,
Eloy

**Comment by nfreear** [comment]
Hi Eloy,

Thanks. I don't need to "compile" the Java sources on the test/live server, as they're already compiled, so I'll work out what Maven goal to run to download the POM dependencies,

 * https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
 * http://maven.apache.org/ref/3.1.0/
 * http://maven.apache.org/ref/3.1.0/maven-embedder/cli.html
 * https://stackoverflow.com/questions/13836978/maven-skip-compile

(Not sure how we've made previous updates like this work -- did we compile on the server? ;) )

Ta,

Nick

---

**Comment by evilfer** [comment]
I just realised it shouldn't be possible to even compile the sources
without the new dependency. So I'm guessing now that maven downloaded the
new JAR files into a specific folder inside the "nquire-web-source" project
when compiling. If you only copy the new compiled classes into the
"nquire-web-compiled" repository project, but don't move the new library
JARs too, that could explains the failure at runtime.

I'm looking at https://github.com/IET-OU/nquire-web-compiled/tree/master/lib,
and it doesn't contain any "google-api-client-1.23.0.jar" file, so maybe
"nquire-web-compiled" is just missing that one jar.

The last time we updated the dependencies was for the OAUTH connectors. But
I just noticed that in a previous commit I updated freechart in
pom.template.xml, but "nquire-web-compiled" still has the old version. So
the libraries need to be updated manually I guess, and pushed into the
"nquire-web-compiled"
repo.

Hopefully the missing jar is the issue, and not some obscure bug with the
Tomcat version or something similar...
Eloy

**Comment by nfreear** [comment]
Hi Eloy / @evilfer,

I've added the missing `google-api-..` and updated `jfreechart` JAR files (do I need to delete the old `jfreechart` JAR?)

* https://github.com/IET-OU/nquire-web-compiled/commit/29f5da7b8aecd8e24df5af350ec8fcd3f8090bae

I've checked out on `pegasos`, restarted Tomcat, and I still get a `404` error.

Is there anything else you can think of please?

Ta,

Nick


---
Cc'ing @kevmcleod

**Comment by evilfer** [comment]
Hi Nick,

I'm out of ideas :(, could you please send me the logs from tomcat?
The error mentiones another log, which I think should be located in the
same folder. This one should have more information.

Eloy

**Pull request merged**
